import { Shipment } from "./Home";
import { Route } from "./Route";

export default function getMockRoutes(shipmentDetails: Shipment): Route[] {
  return [
    {
      id: 1,
      modes: ["Sea", "Land"],
      cost: 1250.5,
      transitTime: 14,
      co2Emissions: "Medium",
      reliability: "High",
      borderCrossings: 2,
      category: "cost", // Most cost-effective option
      // Added detailed route information
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Rotterdam Port, Netherlands",
          mode: "Land",
          vehicle: "Truck LM-4500",
          company: "EuroFreight Logistics",
          departure: "2023-06-15 08:30",
          arrival: "2023-06-15 14:45",
          duration: "6h 15m",
          distance: "320 km",
          borderCrossing: shipmentDetails.origin.includes("Germany")
            ? "Germany-Netherlands"
            : undefined,
        },
        {
          from: "Rotterdam Port, Netherlands",
          to: "New York Harbor, USA",
          mode: "Sea",
          vehicle: "Container Ship MS Atlantic Explorer",
          company: "Maersk Line",
          departure: "2023-06-16 10:00",
          arrival: "2023-06-28 07:30",
          duration: "11d 21h 30m",
          distance: "5,850 km",
          vesselDetails: {
            capacity: "15,000 TEU",
            route: "TA1 - Transatlantic",
            registration: "IMO 9398335",
          },
        },
        {
          from: "New York Harbor, USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck FH-9870",
          company: "American Road Logistics",
          departure: "2023-06-29 09:15",
          arrival: "2023-06-29 15:40",
          duration: "6h 25m",
          distance: "285 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 2,
      modes: ["Air"],
      cost: 2500.75,
      transitTime: 3,
      co2Emissions: "High",
      reliability: "Very High",
      borderCrossings: 1,
      category: "speed", // Fastest delivery option
      // Added detailed route information
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Frankfurt Airport (FRA), Germany",
          mode: "Land",
          vehicle: "Truck MX-2050",
          company: "SpeedLogistics",
          departure: "2023-06-15 11:00",
          arrival: "2023-06-15 13:45",
          duration: "2h 45m",
          distance: "180 km",
          borderCrossing: undefined,
        },
        {
          from: "Frankfurt Airport (FRA), Germany",
          to: "JFK Airport (JFK), New York, USA",
          mode: "Air",
          vehicle: "Boeing 777F Cargo",
          company: "Lufthansa Cargo",
          departure: "2023-06-15 19:45",
          arrival: "2023-06-16 02:30",
          duration: "8h 45m",
          distance: "6,200 km",
          flightDetails: {
            flightNumber: "LH8400",
            aircraft: "Boeing 777F",
            registration: "D-ALFA",
          },
          borderCrossing: "EU-USA Customs",
        },
        {
          from: "JFK Airport (JFK), New York, USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck FH-9870",
          company: "American Road Logistics",
          departure: "2023-06-16 06:30",
          arrival: "2023-06-16 09:15",
          duration: "2h 45m",
          distance: "150 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 3,
      modes: ["Land", "Sea", "Land"],
      cost: 950.25,
      transitTime: 21,
      co2Emissions: "Low",
      reliability: "Medium",
      borderCrossings: 3,
      category: "eco", // Eco-friendly option
      // Added detailed route information
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Berlin Logistics Hub, Germany",
          mode: "Land",
          vehicle: "Train Euro Cargo Express",
          company: "DB Cargo",
          departure: "2023-06-15 14:30",
          arrival: "2023-06-15 20:15",
          duration: "5h 45m",
          distance: "450 km",
          borderCrossing: undefined,
          trainDetails: {
            trainNumber: "CE-4502",
            carriageNumber: "C08",
          },
        },
        {
          from: "Berlin Logistics Hub, Germany",
          to: "Hamburg Port, Germany",
          mode: "Land",
          vehicle: "Truck VT-8900",
          company: "Deutsche LogistikGruppe",
          departure: "2023-06-16 07:00",
          arrival: "2023-06-16 10:30",
          duration: "3h 30m",
          distance: "290 km",
          borderCrossing: undefined,
        },
        {
          from: "Hamburg Port, Germany",
          to: "Montreal Harbor, Canada",
          mode: "Sea",
          vehicle: "Container Ship MS Nordic Voyager",
          company: "MSC Mediterranean Shipping",
          departure: "2023-06-17 16:00",
          arrival: "2023-06-30 08:45",
          duration: "12d 16h 45m",
          distance: "6,100 km",
          vesselDetails: {
            capacity: "9,500 TEU",
            route: "TA3 - North Atlantic",
            registration: "IMO 9754127",
          },
        },
        {
          from: "Montreal Harbor, Canada",
          to: "US-Canada Border Crossing",
          mode: "Land",
          vehicle: "Truck CM-4520",
          company: "CanAm Logistics",
          departure: "2023-07-01 09:30",
          arrival: "2023-07-01 13:45",
          duration: "4h 15m",
          distance: "220 km",
          borderCrossing: "Canada-USA",
        },
        {
          from: "US-Canada Border Crossing",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck US-7720",
          company: "American Road Logistics",
          departure: "2023-07-01 15:00",
          arrival: "2023-07-01 19:30",
          duration: "4h 30m",
          distance: "310 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 4,
      modes: ["Land"],
      cost: 1850.75,
      transitTime: 18,
      co2Emissions: "Medium",
      reliability: "High",
      borderCrossings: 4,
      category: "balanced",
      // Added detailed route information for land-only option
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Berlin, Germany",
          mode: "Land",
          vehicle: "Truck VT-8800",
          company: "Deutsche LogistikGruppe",
          departure: "2023-06-15 06:30",
          arrival: "2023-06-15 12:45",
          duration: "6h 15m",
          distance: "410 km",
          borderCrossing: undefined,
        },
        {
          from: "Berlin, Germany",
          to: "Warsaw, Poland",
          mode: "Land",
          vehicle: "Truck VT-8800",
          company: "Deutsche LogistikGruppe",
          departure: "2023-06-15 14:00",
          arrival: "2023-06-15 20:30",
          duration: "6h 30m",
          distance: "575 km",
          borderCrossing: "Germany-Poland",
        },
        {
          from: "Warsaw, Poland",
          to: "Moscow, Russia",
          mode: "Land",
          vehicle: "Truck VT-8800",
          company: "EuroAsian Logistics",
          departure: "2023-06-16 08:00",
          arrival: "2023-06-17 18:30",
          duration: "1d 10h 30m",
          distance: "1,250 km",
          borderCrossing: "Poland-Belarus, Belarus-Russia",
        },
        {
          from: "Moscow, Russia",
          to: "Vladivostok, Russia",
          mode: "Land",
          vehicle: "Train Trans-Siberian Express",
          company: "Russian Railways",
          departure: "2023-06-18 10:45",
          arrival: "2023-06-25 14:20",
          duration: "7d 3h 35m",
          distance: "9,200 km",
          borderCrossing: undefined,
          trainDetails: {
            trainNumber: "TS-0092",
            carriageNumber: "F17",
          },
        },
        {
          from: "Vladivostok, Russia",
          to: "Beijing, China",
          mode: "Land",
          vehicle: "Truck AS-5600",
          company: "AsiaRoute Logistics",
          departure: "2023-06-26 08:00",
          arrival: "2023-06-28 19:15",
          duration: "2d 11h 15m",
          distance: "1,850 km",
          borderCrossing: "Russia-China",
        },
        {
          from: "Beijing, China",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck CN-2280",
          company: "China Express",
          departure: "2023-06-29 10:30",
          arrival: "2023-06-30 16:45",
          duration: "1d 6h 15m",
          distance: "950 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 5,
      modes: ["Sea"],
      cost: 1100.25,
      transitTime: 28,
      co2Emissions: "Low",
      reliability: "Medium",
      borderCrossings: 0,
      category: "eco",
      // Added detailed route information for sea-only option
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Hamburg Port, Germany",
          mode: "Land",
          vehicle: "Truck DT-4500",
          company: "Deutsche LogistikGruppe",
          departure: "2023-06-15 08:00",
          arrival: "2023-06-15 14:30",
          duration: "6h 30m",
          distance: "380 km",
          borderCrossing: undefined,
        },
        {
          from: "Hamburg Port, Germany",
          to: "Suez Canal, Egypt",
          mode: "Sea",
          vehicle: "Container Ship MS Europa",
          company: "Maersk Line",
          departure: "2023-06-16 13:00",
          arrival: "2023-06-23 10:45",
          duration: "6d 21h 45m",
          distance: "7,800 km",
          vesselDetails: {
            capacity: "18,000 TEU",
            route: "AE1 - Asia-Europe",
            registration: "IMO 9632064",
          },
        },
        {
          from: "Suez Canal, Egypt",
          to: "Singapore Port, Singapore",
          mode: "Sea",
          vehicle: "Container Ship MS Europa",
          company: "Maersk Line",
          departure: "2023-06-24 09:30",
          arrival: "2023-07-06 16:20",
          duration: "12d 6h 50m",
          distance: "8,600 km",
          vesselDetails: {
            capacity: "18,000 TEU",
            route: "AE1 - Asia-Europe",
            registration: "IMO 9632064",
          },
        },
        {
          from: "Singapore Port, Singapore",
          to: "Shanghai Port, China",
          mode: "Sea",
          vehicle: "Container Ship MS Europa",
          company: "Maersk Line",
          departure: "2023-07-07 14:00",
          arrival: "2023-07-12 08:30",
          duration: "4d 18h 30m",
          distance: "4,200 km",
          vesselDetails: {
            capacity: "18,000 TEU",
            route: "AE1 - Asia-Europe",
            registration: "IMO 9632064",
          },
        },
        {
          from: "Shanghai Port, China",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck CN-9900",
          company: "China Express",
          departure: "2023-07-13 10:00",
          arrival: "2023-07-13 17:45",
          duration: "7h 45m",
          distance: "520 km",
          borderCrossing: undefined,
        },
      ],
    },

    // NEW ADDED ROUTES

    // Adding another air route option with different stops
    {
      id: 6,
      modes: ["Air"],
      cost: 2750.8,
      transitTime: 4,
      co2Emissions: "High",
      reliability: "High",
      borderCrossings: 2,
      category: "balanced",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Munich Airport (MUC), Germany",
          mode: "Land",
          vehicle: "Electric Truck E-3500",
          company: "GreenLogistics",
          departure: "2023-06-15 09:00",
          arrival: "2023-06-15 12:30",
          duration: "3h 30m",
          distance: "230 km",
          borderCrossing: undefined,
        },
        {
          from: "Munich Airport (MUC), Germany",
          to: "Dubai International (DXB), UAE",
          mode: "Air",
          vehicle: "Airbus A330F",
          company: "Emirates SkyCargo",
          departure: "2023-06-15 17:30",
          arrival: "2023-06-16 01:15",
          duration: "5h 45m",
          distance: "4,600 km",
          flightDetails: {
            flightNumber: "EK9842",
            aircraft: "Airbus A330F",
            registration: "A6-EFC",
          },
          borderCrossing: "EU-UAE Customs",
        },
        {
          from: "Dubai International (DXB), UAE",
          to: "Newark Liberty (EWR), USA",
          mode: "Air",
          vehicle: "Boeing 777F",
          company: "Emirates SkyCargo",
          departure: "2023-06-16 03:40",
          arrival: "2023-06-16 10:20",
          duration: "14h 40m",
          distance: "11,020 km",
          flightDetails: {
            flightNumber: "EK9201",
            aircraft: "Boeing 777F",
            registration: "A6-EFF",
          },
          borderCrossing: "UAE-USA Customs",
        },
        {
          from: "Newark Liberty (EWR), USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck FT-7200",
          company: "Fast Track Delivery",
          departure: "2023-06-16 13:00",
          arrival: "2023-06-16 16:45",
          duration: "3h 45m",
          distance: "180 km",
          borderCrossing: undefined,
        },
      ],
    },

    // Adding a multi-modal route with air and rail
    {
      id: 7,
      modes: ["Air", "Land"],
      cost: 2200.5,
      transitTime: 5,
      co2Emissions: "Medium-High",
      reliability: "High",
      borderCrossings: 2,
      category: "balanced",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Paris Charles de Gaulle (CDG), France",
          mode: "Land",
          vehicle: "Truck EU-5511",
          company: "Euro Express Freight",
          departure: "2023-06-15 07:15",
          arrival: "2023-06-15 13:30",
          duration: "6h 15m",
          distance: "455 km",
          borderCrossing: "Germany-France",
        },
        {
          from: "Paris Charles de Gaulle (CDG), France",
          to: "Chicago O'Hare (ORD), USA",
          mode: "Air",
          vehicle: "Boeing 747-8F",
          company: "Air France Cargo",
          departure: "2023-06-15 18:20",
          arrival: "2023-06-15 21:30",
          duration: "9h 10m",
          distance: "6,670 km",
          flightDetails: {
            flightNumber: "AF8230",
            aircraft: "Boeing 747-8F",
            registration: "F-GITH",
          },
          borderCrossing: "EU-USA Customs",
        },
        {
          from: "Chicago O'Hare (ORD), USA",
          to: "Chicago Union Station",
          mode: "Land",
          vehicle: "Truck US-3300",
          company: "Cross City Transit",
          departure: "2023-06-16 08:00",
          arrival: "2023-06-16 09:15",
          duration: "1h 15m",
          distance: "45 km",
          borderCrossing: undefined,
        },
        {
          from: "Chicago Union Station",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Rail Cargo Express",
          company: "Amtrak Freight",
          departure: "2023-06-16 11:30",
          arrival: "2023-06-17 14:45",
          duration: "1d 3h 15m",
          distance: "1,200 km",
          trainDetails: {
            trainNumber: "AC-7702",
            carriageNumber: "F22",
          },
          borderCrossing: undefined,
        },
      ],
    },

    // Adding a pure rail option (more eco-friendly)
    {
      id: 8,
      modes: ["Land"],
      cost: 1450.3,
      transitTime: 12,
      co2Emissions: "Low",
      reliability: "Medium-High",
      borderCrossings: 3,
      category: "eco",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Frankfurt Rail Terminal, Germany",
          mode: "Land",
          vehicle: "Truck DL-6620",
          company: "Deutsche LogistikGruppe",
          departure: "2023-06-15 08:45",
          arrival: "2023-06-15 11:30",
          duration: "2h 45m",
          distance: "160 km",
          borderCrossing: undefined,
        },
        {
          from: "Frankfurt Rail Terminal, Germany",
          to: "Paris Gare du Nord, France",
          mode: "Land",
          vehicle: "Deutsche Bahn Cargo Train",
          company: "DB Schenker",
          departure: "2023-06-15 14:00",
          arrival: "2023-06-15 19:15",
          duration: "5h 15m",
          distance: "480 km",
          trainDetails: {
            trainNumber: "DB-9051",
            carriageNumber: "C14",
          },
          borderCrossing: "Germany-France",
        },
        {
          from: "Paris Gare du Nord, France",
          to: "London St Pancras, UK",
          mode: "Land",
          vehicle: "Eurostar Cargo Train",
          company: "Eurostar Logistics",
          departure: "2023-06-16 07:30",
          arrival: "2023-06-16 09:01",
          duration: "1h 31m",
          distance: "453 km",
          trainDetails: {
            trainNumber: "ES-7920",
            carriageNumber: "D03",
          },
          borderCrossing: "France-UK",
        },
        {
          from: "London St Pancras, UK",
          to: "Liverpool Port, UK",
          mode: "Land",
          vehicle: "UK Rail Cargo Express",
          company: "GB Railfreight",
          departure: "2023-06-16 10:30",
          arrival: "2023-06-16 14:45",
          duration: "4h 15m",
          distance: "340 km",
          trainDetails: {
            trainNumber: "GB-4402",
            carriageNumber: "B21",
          },
          borderCrossing: undefined,
        },
        {
          from: "Liverpool Port, UK",
          to: "Halifax Port, Canada",
          mode: "Sea",
          vehicle: "Container Ship MS Atlantic Voyager",
          company: "Hapag-Lloyd",
          departure: "2023-06-17 10:00",
          arrival: "2023-06-24 08:30",
          duration: "6d 22h 30m",
          distance: "4,700 km",
          vesselDetails: {
            capacity: "10,500 TEU",
            route: "North Atlantic Express",
            registration: "IMO 9731987",
          },
        },
        {
          from: "Halifax Port, Canada",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Canadian National Railway",
          company: "CN Rail",
          departure: "2023-06-24 14:00",
          arrival: "2023-06-27 16:30",
          duration: "3d 2h 30m",
          distance: "1,850 km",
          trainDetails: {
            trainNumber: "CN-5501",
            carriageNumber: "A09",
          },
          borderCrossing: "Canada-USA",
        },
      ],
    },

    // Adding a specialized refrigerated transport option for perishable goods
    {
      id: 9,
      modes: ["Air", "Land"],
      cost: 3100.9,
      transitTime: 2,
      co2Emissions: "High",
      reliability: "Very High",
      borderCrossings: 1,
      category: "specialized",
      specializedFor: "perishable",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          fromCoords: [51.505, -0.09],
          to: "Amsterdam Schiphol (AMS), Netherlands",
          mode: "Land",
          vehicle: "Refrigerated Truck RF-5500",
          company: "ColdChain Logistics",
          departure: "2023-06-15 06:00",
          arrival: "2023-06-15 10:30",
          duration: "4h 30m",
          distance: "280 km",
          borderCrossing: "Germany-Netherlands",
          refrigerated: true,
          temperature: "-2°C to +2°C",
        },
        {
          from: "Amsterdam Schiphol (AMS), Netherlands",
          to: "Atlanta Hartsfield (ATL), USA",
          mode: "Air",
          vehicle: "Boeing 777-200F",
          company: "Delta Cargo",
          departure: "2023-06-15 14:15",
          arrival: "2023-06-15 18:30",
          duration: "10h 15m",
          distance: "7,100 km",
          flightDetails: {
            flightNumber: "DL9821",
            aircraft: "Boeing 777-200F",
            registration: "N705GT",
          },
          borderCrossing: "EU-USA Customs",
          refrigerated: true,
          temperature: "0°C to +4°C",
        },
        {
          from: "Atlanta Hartsfield (ATL), USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Refrigerated Truck KW-8800",
          company: "US Cold Transport",
          departure: "2023-06-15 20:00",
          arrival: "2023-06-16 05:45",
          duration: "9h 45m",
          distance: "550 km",
          borderCrossing: undefined,
          refrigerated: true,
          temperature: "-2°C to +2°C",
        },
      ],
    },

    // Adding a specialized secure transport for high-value cargo
    {
      id: 10,
      modes: ["Air", "Land"],
      cost: 3950.0,
      transitTime: 2,
      co2Emissions: "High",
      reliability: "Very High",
      borderCrossings: 1,
      category: "specialized",
      specializedFor: "high-value",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Zurich Airport (ZRH), Switzerland",
          mode: "Land",
          vehicle: "Armored Truck SV-2200",
          company: "SecureVault Transport",
          departure: "2023-06-15 08:00",
          arrival: "2023-06-15 13:45",
          duration: "5h 45m",
          distance: "350 km",
          borderCrossing: "Germany-Switzerland",
          security: "Armed guards, GPS tracking, real-time monitoring",
        },
        {
          from: "Zurich Airport (ZRH), Switzerland",
          to: "New York JFK (JFK), USA",
          mode: "Air",
          vehicle: "Swiss Secure Air Transport",
          company: "SWISS WorldCargo",
          departure: "2023-06-15 17:30",
          arrival: "2023-06-15 20:45",
          duration: "9h 15m",
          distance: "6,400 km",
          flightDetails: {
            flightNumber: "LX8800",
            aircraft: "Airbus A330-300",
            registration: "HB-JHK",
          },
          borderCrossing: "Switzerland-USA Customs",
          security: "Dedicated secure cargo area, constant surveillance",
        },
        {
          from: "New York JFK (JFK), USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Armored Truck BT-6600",
          company: "Brink's Security Transport",
          departure: "2023-06-15 22:30",
          arrival: "2023-06-16 03:15",
          duration: "4h 45m",
          distance: "270 km",
          borderCrossing: undefined,
          security: "Armed escort, secure communication, route monitoring",
        },
      ],
    },

    // Adding another sea route with different stops
    {
      id: 11,
      modes: ["Sea"],
      cost: 1050.8,
      transitTime: 25,
      co2Emissions: "Low",
      reliability: "Medium",
      borderCrossings: 0,
      category: "eco",
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Antwerp Port, Belgium",
          mode: "Land",
          vehicle: "Electric Truck EC-5500",
          company: "EcoFreight",
          departure: "2023-06-15 09:30",
          arrival: "2023-06-15 16:15",
          duration: "6h 45m",
          distance: "370 km",
          borderCrossing: "Germany-Belgium",
        },
        {
          from: "Antwerp Port, Belgium",
          to: "Panama Canal, Panama",
          mode: "Sea",
          vehicle: "Container Ship MS Green Pioneer",
          company: "CMA CGM",
          departure: "2023-06-16 15:00",
          arrival: "2023-06-27 09:30",
          duration: "10d 18h 30m",
          distance: "8,450 km",
          vesselDetails: {
            capacity: "14,000 TEU",
            route: "Atlantic-Pacific Express",
            registration: "IMO 9839272",
          },
        },
        {
          from: "Panama Canal, Panama",
          to: "Long Beach Port, USA",
          mode: "Sea",
          vehicle: "Container Ship MS Green Pioneer",
          company: "CMA CGM",
          departure: "2023-06-28 05:00",
          arrival: "2023-07-08 11:45",
          duration: "10d 6h 45m",
          distance: "5,900 km",
          vesselDetails: {
            capacity: "14,000 TEU",
            route: "Atlantic-Pacific Express",
            registration: "IMO 9839272",
          },
        },
        {
          from: "Long Beach Port, USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Hybrid Truck HT-6200",
          company: "West Coast Green Logistics",
          departure: "2023-07-09 08:00",
          arrival: "2023-07-10 15:30",
          duration: "1d 7h 30m",
          distance: "780 km",
          borderCrossing: undefined,
        },
      ],
    },

    // Add these routes after route id 12 in your App.jsx file
    // New Air-only options to ensure we have fastest and cost-effective for air filter
    {
      id: 13,
      modes: ["Air"],
      cost: 1950.5, // Cheaper air option to be cost-effective when filtering for air only
      transitTime: 3.5,
      co2Emissions: "High",
      reliability: "High",
      borderCrossings: 1,
      category: "cost", // Mark as cost-effective for air
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Berlin Tegel (TXL), Germany",
          mode: "Land",
          vehicle: "Electric Van GE-2200",
          company: "Berlin Express Logistics",
          departure: "2023-06-15 06:00",
          arrival: "2023-06-15 08:30",
          duration: "2h 30m",
          distance: "150 km",
          borderCrossing: undefined,
        },
        {
          from: "Berlin Tegel (TXL), Germany",
          to: "London Heathrow (LHR), UK",
          mode: "Air",
          vehicle: "Airbus A300F",
          company: "Eurocargo Airways",
          departure: "2023-06-15 11:45",
          arrival: "2023-06-15 13:15",
          duration: "1h 30m",
          distance: "950 km",
          flightDetails: {
            flightNumber: "EC4501",
            aircraft: "Airbus A300F",
            registration: "G-EURC",
          },
          borderCrossing: "EU-UK Customs",
        },
        {
          from: "London Heathrow (LHR), UK",
          to: "New York JFK (JFK), USA",
          mode: "Air",
          vehicle: "Boeing 747F",
          company: "TransAtlantic Cargo",
          departure: "2023-06-15 15:30",
          arrival: "2023-06-15 18:45",
          duration: "7h 15m",
          distance: "5,550 km",
          flightDetails: {
            flightNumber: "TA2098",
            aircraft: "Boeing 747F",
            registration: "G-TACB",
          },
          borderCrossing: "UK-USA Customs",
        },
        {
          from: "New York JFK (JFK), USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck US-8877",
          company: "East Coast Logistics",
          departure: "2023-06-15 21:00",
          arrival: "2023-06-16 01:30",
          duration: "4h 30m",
          distance: "280 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 14,
      modes: ["Air"],
      cost: 2250.25,
      transitTime: 2.5, // Faster than other air options to be fastest when filtering air only
      co2Emissions: "High",
      reliability: "Very High",
      borderCrossings: 1,
      category: "speed", // Mark as fastest for air
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Frankfurt Airport (FRA), Germany",
          mode: "Land",
          vehicle: "High-Speed Logistics Van",
          company: "Express Connect",
          departure: "2023-06-15 05:30",
          arrival: "2023-06-15 08:00",
          duration: "2h 30m",
          distance: "220 km",
          borderCrossing: undefined,
        },
        {
          from: "Frankfurt Airport (FRA), Germany",
          to: "New York JFK (JFK), USA",
          mode: "Air",
          vehicle: "Boeing 777X-F",
          company: "Lufthansa Premium Cargo",
          departure: "2023-06-15 10:15",
          arrival: "2023-06-15 13:40",
          duration: "7h 25m",
          distance: "6,200 km",
          flightDetails: {
            flightNumber: "LH8800",
            aircraft: "Boeing 777X-F",
            registration: "D-ALFT",
          },
          borderCrossing: "EU-USA Customs",
          expedited: true,
          priority: "Ultra Priority",
        },
        {
          from: "New York JFK (JFK), USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Premium Delivery Van",
          company: "JFK Express Couriers",
          departure: "2023-06-15 15:00",
          arrival: "2023-06-15 17:45",
          duration: "2h 45m",
          distance: "150 km",
          borderCrossing: undefined,
          expedited: true,
        },
      ],
    },

    // New Sea-only options to ensure we have fastest and cost-effective for sea filter
    {
      id: 15,
      modes: ["Sea"],
      cost: 950.5, // Cheapest sea option
      transitTime: 26,
      co2Emissions: "Low",
      reliability: "Medium",
      borderCrossings: 0,
      category: "cost", // Mark as cost-effective for sea
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Rotterdam Port, Netherlands",
          mode: "Land",
          vehicle: "Truck RT-2233",
          company: "Euro Container Transport",
          departure: "2023-06-15 07:00",
          arrival: "2023-06-15 14:00",
          duration: "7h 00m",
          distance: "410 km",
          borderCrossing: "Germany-Netherlands",
        },
        {
          from: "Rotterdam Port, Netherlands",
          to: "Boston Harbor, USA",
          mode: "Sea",
          vehicle: "Container Ship MS Northern Star",
          company: "Maersk Economy Line",
          departure: "2023-06-16 13:00",
          arrival: "2023-06-30 15:30",
          duration: "14d 2h 30m",
          distance: "5,200 km",
          vesselDetails: {
            capacity: "12,000 TEU",
            route: "North Atlantic Budget Route",
            registration: "IMO 9528392",
          },
        },
        {
          from: "Boston Harbor, USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck US-4411",
          company: "Northeast Cargo Transport",
          departure: "2023-07-01 08:00",
          arrival: "2023-07-01 15:30",
          duration: "7h 30m",
          distance: "350 km",
          borderCrossing: undefined,
        },
      ],
    },
    {
      id: 16,
      modes: ["Sea"],
      cost: 1250.75,
      transitTime: 19, // Faster sea option
      co2Emissions: "Low-Medium",
      reliability: "High",
      borderCrossings: 0,
      category: "speed", // Mark as fastest for sea
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Hamburg Port, Germany",
          mode: "Land",
          vehicle: "Truck HH-9980",
          company: "North German Logistics",
          departure: "2023-06-15 05:30",
          arrival: "2023-06-15 10:45",
          duration: "5h 15m",
          distance: "320 km",
          borderCrossing: undefined,
        },
        {
          from: "Hamburg Port, Germany",
          to: "New York Harbor, USA",
          mode: "Sea",
          vehicle: "High-Speed Container Vessel MV Express Atlantic",
          company: "Hapag-Lloyd Express",
          departure: "2023-06-16 08:00",
          arrival: "2023-06-25 14:30",
          duration: "9d 6h 30m",
          distance: "5,850 km",
          vesselDetails: {
            capacity: "8,000 TEU",
            route: "Express Atlantic Route",
            registration: "IMO 9712426",
            category: "High-Speed Vessel",
          },
        },
        {
          from: "New York Harbor, USA",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck FF-7744",
          company: "Fast Forward Logistics",
          departure: "2023-06-25 17:00",
          arrival: "2023-06-25 22:15",
          duration: "5h 15m",
          distance: "290 km",
          borderCrossing: undefined,
        },
      ],
    },

    // New Land-only options to ensure we have fastest and cost-effective for land filter
    {
      id: 17,
      modes: ["Land"],
      cost: 1250.3, // Cheaper land option
      transitTime: 16,
      co2Emissions: "Medium",
      reliability: "High",
      borderCrossings: 3,
      category: "cost", // Mark as cost-effective for land
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Warsaw, Poland",
          mode: "Land",
          vehicle: "EcoTruck PL-5500",
          company: "Green Road Logistics",
          departure: "2023-06-15 04:30",
          arrival: "2023-06-15 19:45",
          duration: "15h 15m",
          distance: "990 km",
          borderCrossing: "Germany-Poland",
          trainDetails: {
            trainNumber: "ET-1207",
            carriageNumber: "G22",
          },
        },
        {
          from: "Warsaw, Poland",
          to: "Brest, Belarus",
          mode: "Land",
          vehicle: "Rail Cargo Connect",
          company: "EuroAsian Rail",
          departure: "2023-06-16 06:00",
          arrival: "2023-06-16 14:30",
          duration: "8h 30m",
          distance: "550 km",
          borderCrossing: "Poland-Belarus",
          trainDetails: {
            trainNumber: "EAC-8801",
            carriageNumber: "D05",
          },
        },
        {
          from: "Brest, Belarus",
          to: "Moscow, Russia",
          mode: "Land",
          vehicle: "Rail Cargo Express",
          company: "Russian Railways",
          departure: "2023-06-16 16:00",
          arrival: "2023-06-17 10:30",
          duration: "18h 30m",
          distance: "1,050 km",
          borderCrossing: "Belarus-Russia",
          trainDetails: {
            trainNumber: "RU-1104",
            carriageNumber: "H11",
          },
        },
        {
          from: "Moscow, Russia",
          to: "Vladivostok, Russia",
          mode: "Land",
          vehicle: "Trans-Siberian Railway Budget Express",
          company: "Russian Railways",
          departure: "2023-06-18 08:00",
          arrival: "2023-06-25 15:30",
          duration: "7d 7h 30m",
          distance: "9,200 km",
          trainDetails: {
            trainNumber: "TS-9900",
            carriageNumber: "E22",
          },
        },
        {
          from: "Vladivostok, Russia",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "Truck VL-2244",
          company: "Far East Logistics",
          departure: "2023-06-26 06:00",
          arrival: "2023-07-01 15:45",
          duration: "5d 9h 45m",
          distance: "2,200 km",
          borderCrossing: "Russia-China",
        },
      ],
    },
    {
      id: 18,
      modes: ["Land"],
      cost: 1650.8,
      transitTime: 10, // Faster land option
      co2Emissions: "Medium-High",
      reliability: "Very High",
      borderCrossings: 2,
      category: "speed", // Mark as fastest for land
      detailedRoute: [
        {
          from: shipmentDetails.origin,
          to: "Berlin, Germany",
          mode: "Land",
          vehicle: "High-Speed Transfer Van",
          company: "Berlin Express",
          departure: "2023-06-15 05:00",
          arrival: "2023-06-15 09:30",
          duration: "4h 30m",
          distance: "390 km",
          borderCrossing: undefined,
        },
        {
          from: "Berlin, Germany",
          to: "Budapest, Hungary",
          mode: "Land",
          vehicle: "Express Train Central Europe",
          company: "EU Express Railways",
          departure: "2023-06-15 11:00",
          arrival: "2023-06-15 17:45",
          duration: "6h 45m",
          distance: "870 km",
          borderCrossing: "Germany-Austria-Hungary",
          trainDetails: {
            trainNumber: "EC-3300",
            carriageNumber: "A01",
            category: "High-Speed",
          },
        },
        {
          from: "Budapest, Hungary",
          to: "Istanbul, Turkey",
          mode: "Land",
          vehicle: "Express Train Eastern Europe",
          company: "EuroTurk Railways",
          departure: "2023-06-15 19:30",
          arrival: "2023-06-16 09:15",
          duration: "13h 45m",
          distance: "1,050 km",
          borderCrossing: "Hungary-Serbia-Bulgaria-Turkey",
          trainDetails: {
            trainNumber: "ET-5500",
            carriageNumber: "B07",
          },
        },
        {
          from: "Istanbul, Turkey",
          to: shipmentDetails.destination,
          mode: "Land",
          vehicle: "High-Speed Rail Express",
          company: "Trans-Asian Railway Network",
          departure: "2023-06-16 12:00",
          arrival: "2023-06-25 16:30",
          duration: "9d 4h 30m",
          distance: "6,500 km",
          trainDetails: {
            trainNumber: "TAR-8809",
            carriageNumber: "S11",
            category: "Premium Express",
          },
        },
      ],
    },
  ];
}
